#ifndef QXMLSERIALIZATION_GLOBAL_H
#define QXMLSERIALIZATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QXMLSERIALIZATION_LIBRARY)
#  define QXMLSERIALIZATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QXMLSERIALIZATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QXMLSERIALIZATION_GLOBAL_H
